- hosts: localhost
  become: true
  vars:
    docker_distribution: "'Pop!_OS'"
  tasks:
    - name: Install vim
      apt: name=vim
        
    - name: Add Google APT package key
      become: yes
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub

    - name: Add Google Chrome APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Google Chrome (Linux)
      become: yes
      apt:
        package: google-chrome-stable
        
