- hosts: localhost
  become: true
  vars:
    docker_distribution: "ubuntu"
    current_user: "luiscberrocal"
    version: 2020.03.04
    download_folder: /home/{{ current_user }}/Downloads
    docker_installer: "{{ download_folder }}/dropbox_{{ version }}_amd64.deb"
    docker_url: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_{{ version }}_amd64.deb"
  tasks:
    - name: Install vim
      apt:
        name: vim-nox
        
    - name: Add Google APT package key
      become: yes
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub

    - name: Add Google Chrome APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Google Chrome (Linux)
      become: yes
      apt:
        package: google-chrome-stable

    - name: Install docker subtasks
      include_tasks: ./packages/docker.yml

    - name: Install dropbox subtasks
      include_tasks: ./packages/dropbox.yml

    - name: Install keepass subtasks
      include_tasks: ./packages/keepass.yml
        
