- name: Anaconda 3 installation
  hosts: 127.0.0.1
  connection: local

  vars:
    conda_ver: 2020.11
    download_folder: "{{ ansible_facts.env.HOME }}/Downloads"
    installer_file: "{{ download_folder }}/Anaconda3-{{ conda_ver }}-Linux-x86_64.sh"
    installation_folder: /opt/anaconda3
    
  tasks:
    - name: Prerequisites for Anaconda
      apt:
        name: ["libgl1-mesa-glx", "libegl1-mesa", "libxrandr2", "libxrandr2", "libxss1", "libxcursor1",
               "libxcomposite1", "libasound2", "libxi6", "libxtst6"]
        state: present
      when: ansible_os_family == "Debian"

    - name: Check for downloaded file in {{ download_folder }}
      stat:
        path: "{{ installer_file }}"
      register: installer_file_info
    - debug:
        msg: Test {{ installer_file_info }}
    - name: Download anaconda installer {{ conda_ver }}
      when:  not installer_file_info.stat.exists
      get_url:
        url: "https://repo.anaconda.com/archive/Anaconda3-{{ conda_ver }}-Linux-x86_64.sh"
        dest: "{{ installer_file }}"
        checksum: "md5:4cd48ef23a075e8555a8b6d0a8c4bae2"
        mode: 0550
    - name: Create conda folder in {{ installation_folder }}
      become: yes
      file:
        path: "{{ installation_folder }}"
        state: directory
        owner: root
        mode: 755
        recurse: yes
    - name: Run anaconda installer
      shell: "{{ installer_file }} -b -u -p {{ installation_folder }}"
    - name: Add {{installation_folder}}/bin to path
      become: yes
      lineinfile: 
        dest: "{{ansible_facts.env.HOME}}/.bashrc"
        state: present
        insertafter: 'EOF'
        line: "export PATH=$PATH:{{ installation_folder }}/bin" 
    - name: conda - read permission for all
      become: True
      file:
        path: "{{ installation_folder }}"
        mode: +r
        recurse: yes
    - name: conda - execution permission for all
      become: True
      file:
        path: "{{ installation_folder }}"
        mode: +x
        recurse: yes

   
