- name: Dropbox
  hosts: 127.0.0.1
  connection: local
  vars:
    version: 2020.03.04
    download_folder: /home/lberrocal/Downloads
    installer_file: "{{ download_folder }}/dropbox_{{ version }}_amd64.deb"
    deb_url: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_{{ version }}_amd64.deb"
  tasks:
    - name: Check for downloaded file
      stat:
        path: "{{ installer_file }}"
      register: installer_file_info

    - name: Download Dropbox installer
      when: not installer_file_info.stat.exists
      get_url:
        url: "{{ deb_url }}"
        dest: "{{ installer_file }}"
        mode: 0550
    - name: Install Dropbox
      apt:
        deb: "{{ installer_file }}"
