- name: Gitkrakken
  hosts: 127.0.0.1
  connection: local
  vars:
    download_folder: /home/lberrocal/Downloads
    installer_file: "{{ download_folder }}/gitkraken-amd64.deb"
    deb_url: "https://release.gitkraken.com/linux/gitkraken-amd64.deb"
  tasks:
    - name: Check for downloaded file
      stat:
        path: "{{ installer_file }}"
      register: installer_file_info

    - name: Download Gitkrakken installer
      when: not installer_file_info.stat.exists
      get_url:
        url: "{{ deb_url }}"
        dest: "{{ installer_file }}"
        mode: 0550
    - name: Install Gitkrakken
      apt:
        deb: "{{ installer_file }}"