- name: Linux graphic utilities
  hosts: 127.0.0.1
  connection: local

  vars:
    download_folder: "{{ ansible_facts.env.HOME }}/Downloads"

  tasks:
    - name: Print variables
      debug:
        msg: "Family: {{ansible_os_family}}"
    - name: Graphic utils
      become: yes
      apt:
        name: [ "stacer"]
        state: present
        update_cache: yes
      when: ansible_os_family == "Pop!_OS"