- name: JetBrains
  hosts: 127.0.0.1
  connection: local

  vars:
    pycharm_ver: 2020.3
    pycharm_archive: /home/lberrocal/Downloads/pycharm-professional-{{ pycharm_ver }}.tar.gz

  tasks:
    - name: Extract JetBrains Pycharm
      unarchive:
        src: https://download.jetbrains.com/python/pycharm-professional-{{ pycharm_ver }}.tar.gz
        dest: /home/lberrocal/Downloads
        remote_src: yes
        creates: /home/lberrocal/Downloads/pycharm-{{ pycharm_ver }}
    - name: Install Pycharm
      become: yes
      copy:
        src: /home/lberrocal/Downloads/pycharm-{{ pycharm_ver }}
        dest: /usr/local/bin/pycharm
        mode: 0755
        remote_src: yes
     
