- name: JetBrains
  hosts: 127.0.0.1
  connection: local

  vars:
    conda_ver: 2020.11
    download_folder: /home/lberrocal/Downloads
    installer_file: "{{ download_folder }}/Anaconda3-{{ conda_ver }}-Linux-x86_64.sh"
    installation_folder: /opt/anaconda3

  tasks:
    - name: Add {{installation_folder}}/bin to path
      become: yes
      lineinfile: 
        dest: /home/lberrocal/.bashrc
        state: present
        insertafter: 'EOF'
        line: "export PATH=$PATH:{{ installation_folder }}/bin" 
    
     
